name: verify_local_purchase
description: A Flutter package for verifying in-app purchases and subscriptions locally on device with Apple App Store and Google Play Store.
version: 2.0.0
homepage: https://github.com/andrelucassvt/verify_local_purchase
repository: https://github.com/andrelucassvt/verify_local_purchase
issue_tracker: https://github.com/andrelucassvt/verify_local_purchase/issues

topics:
  - in-app-purchase
  - app-store
  - google-play
  - subscription
  - verification

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  app_store_server_sdk: ^1.2.10
  googleapis_auth: ^2.0.0
  http: ^1.6.0
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

platforms:
  android:
  ios:
  macos:
